version: "2.1"
services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:10.5.17
    container_name: mariadb
    environment:
      - PUID=1024
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/lab/src/comicrack-docker/mariadb:/config
    expose:
      - "3306"
    restart: unless-stopped
    networks:
      - comicrack
  comicrack:
    image: pezhore/comicrack:latest
    container_name: comicrack
    depends_on:
      - mariadb
    environment:
      - PUID=1024
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/lab/src/comicrack-docker/local:/wine32/drive_c/users/abc/AppData/Local/cYo/ComicRack
      - /home/lab/src/comicrack-docker/roaming:/wine32/drive_c/users/abc/AppData/Roaming/cYo/ComicRack
      - /mnt/ds1618/comics:/config/comics
    ports:
      - 3001:3001
    networks:
      - comicrack
networks:
  comicrack:
    name: comicrack
